custom_header_links_with_submenu:
  type: objects
  default: []
  schema:
    name: "link"
    identifier: text
    properties:
      text:
        type: string
        required: true
      title:
        type: string
      url:
        type: string
        required: true
      target:
        type: enum
        choices:
          - blank
          - self
      subLinks:  # This field holds the submenus
        type: array
        items:
          type: object
          properties:
            text:
              type: string
              required: true
            url:
              type: string
              required: true
            target:
              type: enum
              choices:
                - blank
                - self
              default: self
